### ISSUE TITLE
怎么让弹出框可以被拖动

### ISSUE THREAD

**Issue by introspection3** [aui/angular-popups#26]
怎么让弹出框可以被拖动

**Comment by introspection3** [comment]
@aui 楼主,这显然不支持,我也没有想过你会去支持这个很重要但对你来说估计很难的东西,
只希望楼主给予提示,如果做可以让它支持,现在面临选型问题

**Comment by aui** [comment]
关闭问题的原因：你问了无关的问题。

拖拽应该是其他指令来控制的，自己写也很简单。

**Comment by introspection3** [comment]
@aui 我和其他弹框中使用者的人一样表示怀疑，通过指令是否可以，ngDrag之类的。
其中还涉及到scope数据的问题，楼主估计低估了事情的难度

**Comment by aui** [comment]
如果你一开始以谦逊的心态、提一个有建设性的问题，或许我会帮助你。如果只是要现成的代码，那还是算了。拖拽、拖拽指令还真的是一个随手就能实现的事（和scope没半毛钱关系）
