### ISSUE TITLE
无法显示弹窗

### ISSUE THREAD

**Issue by alvisisme** [aui/angular-popups#27]
## 复现环境：

Microsoft Edge
版本 90.0.818.42 (官方内部版本) (64 位)

Google Chrome
版本 90.0.4430.85（正式版本） （64 位）

## 复现步骤

演示站点 https://aui.github.io/angular-popups/example/dialog-ng-if.html 点击显示弹框的按钮

弹窗均不能显示。

**Comment by nxjniexiao** [comment]
@alvisisme 把源码里面的`document.createElement("popup")`改成`document.createElement("div")`。

**Comment by alvisisme** [comment]
@nxjniexiao 改了，高版本浏览器内置了popup元素导致样式冲突了。
